### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by illarionds** [maddox/dasher#104]
Hi, first time poster and no expert on Linux, so please excuse any rookie mistakes!  (And indeed apologies if this is the wrong place for this)

I'm using Ubuntu 16.04, and all I have otherwise done on it since installation is install Home Assistant.

I have followed the instructions at https://github.com/maddox/dasher, but got stuck (I believe) due to a different/conflicting version of nodejs.

A more Linux savvy friend walked me through purging npm, nodejs and nodejs-legacy, and after that I can get as far as `npm install` without errors.  But when I actually try and run dasher, I get the following log.

My friend believes everything is sorted with the dependencies, and this bit in the log is accurate:

> 23 error Failed at the dasher@1.4.1 start script 'node app.js'.
> 23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dasher package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js

[npm-debug.log](https://github.com/maddox/dasher/files/1503046/npm-debug.log)

Very appreciative if anyone can help!

**Comment by hfidek** [comment]
same thing here.
still trying to find a solution

**Comment by WagnerBeccard** [comment]
Here too:

`sudo npm run start

> dasher@1.4.1 start /home/pi/dasher
> node app.js

warning: SIOCGIFADDR: en0: No such device - this may not actually work
[Error: SIOCGIFHWADDR: No such device]
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/home/pi/dasher/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/home/pi/dasher/node_modules/node-dash-button/index.js:28:15)
    at register (/home/pi/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/home/pi/dasher/lib/dasher.js:14:21)
    at Object.<anonymous> (/home/pi/dasher/app.js:8:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.4.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dasher@1.4.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/npm-debug.log
`

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart dasher@1.4.1
6 info start dasher@1.4.1
7 verbose unsafe-perm in lifecycle true
8 info dasher@1.4.1 Failed to exec start script
9 verbose stack Error: dasher@1.4.1 start: `node app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid dasher@1.4.1
11 verbose cwd /home/pi/dasher
12 error Linux 4.9.59-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error dasher@1.4.1 start: `node app.js`
17 error Exit status 1
18 error Failed at the dasher@1.4.1 start script 'node app.js'.
18 error This is most likely a problem with the dasher package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app.js
18 error You can get their info via:
18 error     npm owner ls dasher
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]



pi@hassbian:~/dasher $ npm owner ls dasher
npm <npm@npmjs.com>
`

is the project suspended?
