### ISSUE TITLE
Error: Socket hang up

### ISSUE THREAD

**Issue by atomicpapa** [maddox/dasher#106]
I just received my first button today, so I am in the process of setting it up.  I am running Home Assistant .59.2 on an Ubuntu 16.04 server that sits behind a purchased SSL cert.  Dasher is running on the same machine as HASS. Any ideas?

When I press my dash button, I get the following error:

 XXX pressed. Count: 8
[2017-12-10T01:08:09.188Z] there was an error
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

My config is as follows:

{"buttons":[
  {
    "name": "Dudes Meds",
    "address": "fc:a6:67:2b:12:43",
    "timeout": "60000",
    "protocol": "udp",
    "url": "https://ssl.hass.address/api/services/input_boolean/turn_on",
    "method": "POST",
    "headers": {"x-ha-access": "password"},
    "body": "{\"entity_id\": \"input_boolean.dude_meds\"}"
  }
 ]}

Also tried last line like this, with same error:

    "body": {"entity_id": "input_boolean.dude_meds"}

**Comment by silversegarra** [comment]
Hello, did you solved?
