### ISSUE TITLE
Unable to install on Raspberry Pi

### ISSUE THREAD

**Issue by Kallb123** [maddox/dasher#110]
It appears the setup guide is now out of date as the process is failing.

I tried with and without the node_latest_armhf.deb update step.

I firstly see:

`npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.1","npm":"2.14.7"})`

which I suppose means the latest armhf node version isn't up to date enough.

It continues and then I see:

```
> socketwatcher@0.3.0 install /home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'

> pcap@2.0.0 install /home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/.node-gyp"
make: Entering directory '/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
pcap_binding.target.mk:89: recipe for target 'Release/obj.target/pcap_binding/pcap_binding.o' failed
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/dasher/dasher/node_modules/node-dash-button/node_modules/pcap
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/dasher/npm-debug.log
```

**Comment by prierafor** [comment]
Hi, I think this project is out of date.
After few fails, I went with https://github.com/nekmo/amazon-dash, wich works perfectly

**Comment by schneekluth** [comment]
This issue occured on my Pi3 only with Node v10. Dasher runs fine with Node v8. Good luck.
.

**Comment by 21ma** [comment]
I also got the same error.
Cause in my environment, `libpcap-dev` was not installed.

The following pages are helpful.
https://github.com/maddox/dasher/wiki/Installing-Dasher-on-a-Raspberry-Pi

My environment
- Raspberry Pi 3 B +
- Linux raspberrypi 4.14.50 - v 7 + # 1122 SMP Tue Jun 19 12: 26: 26 BST 2018 armv 7 l GNU / Linux
- node 10.6.0 (n package)
