### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by keithschm** [maddox/dasher#114]
anyone else have this?

`TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at doRequest (/home/dasher/lib/dasher.js:61:14)
    at Readable.<anonymous> (/home/dasher/lib/dasher.js:31:7)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
    at PcapSession.<anonymous> (/home/dasher/node_modules/node-dash-button/index.js:87:28)
    at emitOne (events.js:116:13)
    at PcapSession.emit (events.js:211:7)
    at PcapSession.on_packet_ready (/home/dasher/node_modules/pcap/pcap.js:99:10)
`

**Comment by maddox** [comment]
What does your config look like?

**Comment by keithschm** [comment]
I removed private info and replaced with -

`{"buttons":[
  {
    "name": "Debug Dash Button",
    "address": "f0:27:2d:d0:1b:e9",
    "debug": true
  },
  
  {
  	"name": "ifttt",
    "address": "f0:27:2d:d0:1b:e9",
    "url": "https://maker.ifttt.com/trigger/--------/with/key/---------------",
    "method": "POST",
    "debug": false
  }
]}
`

**Comment by keithschm** [comment]
It is odd. If I hard code the urlin the dasher.js file it works fine.
