### ISSUE TITLE
NPM start issues

### ISSUE THREAD

**Issue by Schaddow** [maddox/dasher#115]
Anyone having the same issue?

> pi@JackPi:~/dasher $ sudo npm run start
> 
> > dasher@1.4.1 start /home/pi/dasher
> > node app.js
> 
> module.js:427
>     throw err;
>     ^
> 
> SyntaxError: /home/pi/dasher/config/config.json: Unexpected string
>     at Object.parse (native)
>     at Object.Module._extensions..json (module.js:424:27)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/pi/dasher/app.js:2:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
> 
> npm ERR! dasher@1.4.1 start: `node app.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the dasher@1.4.1 start script.
> npm ERR! This is most likely a problem with the dasher package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node app.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls dasher
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 4.9.80-v7+
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
> npm ERR! cwd /home/pi/dasher
> npm ERR! node -v v4.8.2
> npm ERR! npm -v 1.4.21
> npm ERR! code ELIFECYCLE
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/dasher/npm-debug.log

**Comment by marclefevre** [comment]
I see this too on a stretch version of hassbian:

```
pi@hassbian:~/dasher $ sudo npm run start

> dasher@1.4.1 start /home/pi/dasher
> node app.js

module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.4.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dasher@1.4.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/npm-debug.log
```

**Comment by lam560** [comment]
same here

**Comment by ChoOo7** [comment]
Same here

**Comment by lam560** [comment]
This project is too old.
I found a solution : here is a similar project up to date, very simple to install, fast support and working nice !

https://github.com/Nekmo/amazon-dash

**Comment by maddox** [comment]
@lam560 this is great! I'll link to it in the README.

Sorry folks, but I no longer use this project or Dash buttons at all in my setup. I just found their latency and their general way of working to not be a great solution as a smart button.

**Comment by ChoOo7** [comment]
+1 ! Thanks
