### ISSUE TITLE
Please help...Error with "sudo npm run start". What should I do to fix?

### ISSUE THREAD

**Issue by joeyflores37** [maddox/dasher#16]
joey@joey-GM5664:~$ cd /home/joey/dasher
joey@joey-GM5664:~/dasher$ sudo npm run start

> dasher@1.1.1 start /home/joey/dasher
> node app.js

module.js:428
    throw err;
    ^

SyntaxError: /home/joey/dasher/config/config.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:425:27)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/joey/dasher/app.js:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.1.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joey/dasher/npm-debug.log
joey@joey-GM5664:~/dasher$ 

Here is the npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dasher@1.1.1~prestart: dasher@1.1.1
6 silly lifecycle dasher@1.1.1~prestart: no script for prestart, continuing
7 info lifecycle dasher@1.1.1~start: dasher@1.1.1
8 verbose lifecycle dasher@1.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle dasher@1.1.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/joey/dasher/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle dasher@1.1.1~start: CWD: /home/joey/dasher
11 silly lifecycle dasher@1.1.1~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle dasher@1.1.1~start: Returned: code: 1  signal: null
13 info lifecycle dasher@1.1.1~start: Failed to exec start script
14 verbose stack Error: dasher@1.1.1 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid dasher@1.1.1
16 verbose cwd /home/joey/dasher
17 error Linux 4.4.0-21-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error dasher@1.1.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the dasher@1.1.1 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dasher package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dasher
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dasher
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by spampooper** [comment]
Did you get this figured out? 

The first error appears to be that your config file has an invalid character. The character appears to be a ]

**Comment by djnilse** [comment]
Just happend to me, you may have a comma (",") too much.
The one after your last device needs to be removed
