### ISSUE TITLE
sudo npm run start

### ISSUE THREAD

**Issue by sman1** [maddox/dasher#18]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart dasher@1.1.1
6 info start dasher@1.1.1
7 verbose unsafe-perm in lifecycle true
8 info dasher@1.1.1 Failed to exec start script
9 verbose stack Error: dasher@1.1.1 start: `node app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid dasher@1.1.1
11 verbose cwd /home/pi/Dasher/dasher
12 error Linux 4.4.11-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error dasher@1.1.1 start: `node app.js`
17 error Exit status 1
18 error Failed at the dasher@1.1.1 start script 'node app.js'.
18 error This is most likely a problem with the dasher package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs dasher
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls dasher
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by drewksparks** [comment]
Also having this same issue, even reinstalled nodejs to make sure that wasn't the problem.

**Comment by matthiasmeta** [comment]
same

**Comment by wastedwrath** [comment]
Having the same issue.

**Comment by drewksparks** [comment]
@maddox any thoughts?

**Comment by maddox** [comment]
I'm honestly not sure. I just re-installed all the packages and tried to spin it up and it worked for me on OS X 10.11 with node version 5.7.1

**Comment by ryankne** [comment]
I'm pretty sure I have the same issue on Ubuntu 14.04 as well as an additional error.

Here is my output:


> dasher@1.1.1 start /home/ryan/dasher
> node app.js

module.js:427
    throw err;
    ^

SyntaxError: /home/ryan/dasher/config/config.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ryan/dasher/app.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dasher@1.1.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryan/dasher/npm-debug.log
ryan@tasha:~/dasher$ apt-get install nodejs
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
ryan@tasha:~/dasher$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-34 linux-headers-4.2.0-34-generic linux-headers-4.2.0-35
  linux-headers-4.2.0-35-generic linux-headers-4.2.0-36
  linux-headers-4.2.0-36-generic linux-headers-4.2.0-38
  linux-headers-4.2.0-38-generic linux-image-4.2.0-34-generic
  linux-image-4.2.0-35-generic linux-image-4.2.0-36-generic
  linux-image-4.2.0-38-generic linux-image-extra-4.2.0-34-generic
  linux-image-extra-4.2.0-35-generic linux-image-extra-4.2.0-36-generic
  linux-image-extra-4.2.0-38-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
ryan@tasha:~/dasher$
