### ISSUE TITLE
Find_button Error

### ISSUE THREAD

**Issue by CCOSTAN** [maddox/dasher#3]
find_button is throwing an error.  Here's the log with the libpcap-dev installed, `npm install` completed and then the traceback.

```bash
Setting up libpcap-dev (1.3.0-1) ...
(homeassistant) pi@carlo-pi ~/dasher $ npm install
\
> socketwatcher@0.2.1 install /home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'

> pcap@2.0.1 install /home/pi/dasher/node_modules/node-dash-button/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/pcap_session.o
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  COPY Release/pcap_binding.node
make: Leaving directory '/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/build'
node-dash-button@0.1.5 node_modules/node-dash-button
âââ underscore@1.8.3
âââ pcap@2.0.1 (nan@1.6.2, socketwatcher@0.2.1)
(homeassistant) pi@carlo-pi ~/dasher $ cd script/
(homeassistant) pi@carlo-pi ~/dasher/script $ ls
bootstrap  find_button  install  restart  server  uninstall  upgrade
(homeassistant) pi@carlo-pi ~/dasher/script $ sudo ./find_button
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/pi/dasher/script/node_modules/node-dash-button/bin/findbutton'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by maddox** [comment]
You're in the wrong directory. You should be running `script/find_button` from the root of the repo.

**Comment by CCOSTAN** [comment]
:doh:
