### ISSUE TITLE
Errors during 'sudo npm run start' on Mac OSX Sierra

### ISSUE THREAD

**Issue by adamowen** [maddox/dasher#32]
**I've tried 3 different versions of NodeJS, and still get the same error below;**

Any chance this is a known issue?

Adams-MacBook-Pro:dasher adamowen$ sudo npm run start

> dasher@1.1.1 start /Users/adamowen/dasher
> node app.js

module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adamowen/dasher/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.1.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamowen/dasher/npm-debug.log

**Comment by adamowen** [comment]
I was able to fix the error above by re-installing dasher, however I now get:

SyntaxError: /Users/adamowen/dasher/dasher/config/config.json: Unexpected token “
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adamowen/dasher/dasher/app.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by i-am-chris** [comment]
is your node version. if you downgraded, this happens. Found out on the hard way 👎
