### ISSUE TITLE
Cheapo SSL cert not trusted. 

### ISSUE THREAD

**Issue by CCOSTAN** [maddox/dasher#38]
Looks like my 5 buck a year certificate from SSLS.COM is throwing some sort of error when hitting Home-Assistant. 

```bash

[2016-11-23T20:54:36.146Z] Brooklyn DASH pressed.
[2016-11-23T20:54:36.559Z] there was an error
{ [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
/home/pi/dasher/lib/dasher.js:46
    if (response && response.statusCode < 200 || response.statusCode > 299) {
                                                         ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.onResponse [as _callback] (/home/pi/dasher/lib/dasher.js:46:58)
    at self.callback (/home/pi/dasher/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/pi/dasher/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
```

it looks like this require module might fix the issue for people with broken chains (as in my case).

https://github.com/Daplie/node-ssl-root-cas

Any Shot of incorporating this fix?
Thanks

**Comment by CCOSTAN** [comment]
I actually just combined all my certs..  All is good now..

**Comment by nathanm412** [comment]
I'm having a similar issue. My cert is good, but doesn't work at home as my OnHub router doesn't do NAT loopback, so I have to use the IP address to access the server. Any other ways of fixing this with an option through dasher to just accept the bad cert?
