### ISSUE TITLE
Doesn't start - seems to want to use en0 instead of wlan0

### ISSUE THREAD

**Issue by rhortal** [maddox/dasher#40]
sudo npm run start

> dasher@1.1.1 start /home/pi/dasher
> node app.js

warning: SIOCGIFADDR: en0: No such device - this may not actually work
Error: SIOCGIFHWADDR: No such device
    at Error (native)
    at new PcapSession (/home/pi/dasher/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/home/pi/dasher/node_modules/pcap/pcap.js:123:12)
    at create_session (/home/pi/dasher/node_modules/node-dash-button/index.js:24:28)
    at register (/home/pi/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/home/pi/dasher/lib/dasher.js:12:21)
    at Object.<anonymous> (/home/pi/dasher/app.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/home/pi/dasher/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/home/pi/dasher/node_modules/node-dash-button/index.js:28:15)
    at register (/home/pi/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/home/pi/dasher/lib/dasher.js:12:21)
    at Object.<anonymous> (/home/pi/dasher/app.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Linux 4.1.19v7-aufs
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.1.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/npm-debug.log
[npm-debug.log.txt](https://github.com/maddox/dasher/files/611856/npm-debug.log.txt)

**Comment by rhortal** [comment]
How do I choose what network interface to use? I'm trying on Raspberry Pi 3, running latest raspbian

**Comment by rbflurry** [comment]
In your button config specify the interface or remove the line all together.

{"buttons":[
  {
    "name": "Notify",
    "address": "43:02:dc:b2:ab:23",
    **"interface": "en0",**
    "timeout": "60000",
    "url": "https://maker.ifttt.com/trigger/Notify/with/key/5212ssx2k23k2k",
    "method": "POST",
    "json": true,
    "body": {"value1": "any value", "value2": "another value", "value3": "wow, even more value"}
  },
  {
