### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by LondonTTB** [maddox/dasher#51]
New to Pi, so this is confusing for me. Can anyone help, this is what I get when running npm install.

pi@magicmirror:~/dasher $ npm install

> socketwatcher@0.3.0 install /home/pi/dasher/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/home/pi/dasher/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/home/pi/dasher/node_modules/socketwatcher/build'

> pcap@2.0.0 install /home/pi/dasher/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/home/pi/dasher/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
pcap_binding.target.mk:93: recipe for target 'Release/obj.target/pcap_binding/pcap_binding.o' failed
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/home/pi/dasher/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.37-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/dasher/node_modules/pcap
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.37-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/npm-debug.log
pi@magicmirror:~/dasher $ node -v
v6.9.2
pi@magicmirror:~/dasher $ npm -v
3.10.9
pi@magicmirror:~/dasher $

**Comment by michaellee1019** [comment]
You probably have the line "interface": "en0", somewhere in your configuration file. You can remove all interface lines to have dasher scan the default connected network driver or put in a specific driver name . You can list out all installed network drivers with the linux command "ip link show"
