### ISSUE TITLE
Fresh Raspbian Not Installing

### ISSUE THREAD

**Issue by quavoce** [maddox/dasher#53]
I've tried to install dasher on both the lite and full versions on a clean Raspbian build using image 2016-09-23-raspbian-jessie, but neither have worked.

I also tried sudo npm install -g npm as suggested in another thread, and as you can see in the logs it stopped the "npm WARN engine" errors, but the install still failed.

The pastebin log shows everything entered after a fresh raspbian install:

http://pastebin.com/y7dAzZ1Z

**Comment by quavoce** [comment]
duh - I needed to use "sudo npm install" :)

**Comment by quavoce** [comment]
Ok, looks like it mostly installed ok, but there were errors:

```
pi@raspberrypi:~/dasher $ sudo npm install
npm WARN npm npm does not support Node.js v0.10.29
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/

> socketwatcher@0.3.0 install /home/pi/dasher/node_modules/socketwatcher
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/dasher/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/home/pi/dasher/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/home/pi/dasher/node_modules/socketwatcher/build'

> pcap@2.0.0 install /home/pi/dasher/node_modules/pcap
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/dasher/node_modules/pcap/.node-gyp"
make: Entering directory '/home/pi/dasher/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/pcap_session.o
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  COPY Release/pcap_binding.node
make: Leaving directory '/home/pi/dasher/node_modules/pcap/build'
dasher@1.1.1 /home/pi/dasher
└─┬ node-dash-button@0.6.1
  ├─┬ pcap@2.0.0  (git+https://github.com/mranney/node_pcap.git#d920204745c8b00ef4b7a3fe27d902b263cdb70f)
  │ ├── nan@2.5.0
  │ └── socketwatcher@0.3.0
  └── underscore@1.8.3
```

And now when I try to run the find_button command, the following occurs:

```
pi@raspberrypi:~/dasher/script $ ./find_button

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/pi/dasher/script/node_modules/node-dash-button/bin/findbutton'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
pi@raspberrypi:~/dasher/script $ sudo ./find_button

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/pi/dasher/script/node_modules/node-dash-button/bin/findbutton'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by quavoce** [comment]
Looking to address the Nodejs being unsupported, it seems raspbian only has an old version:

```
pi@raspberrypi:~/dasher/script $ apt list -a nodejs
Listing... Done
nodejs/stable,now 0.10.29~dfsg-2 armhf [installed,automatic]
```

**Comment by quavoce** [comment]
Hmm, so I was able to update to the latest nodejs, and install didn't give any errors, but the find_button still doesn't work. :(

```
pi@raspberrypi:~/dasher/script $ node -v
v0.10.29

pi@raspberrypi:~/dasher/script $ curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

## Installing the NodeSource Node.js v7.x repo...

pi@raspberrypi:~/dasher/script $ node -v
v7.3.0

pi@raspberrypi:~/dasher $ sudo npm install
pi@raspberrypi:~/dasher $

pi@raspberrypi:~/dasher $ cd script/
pi@raspberrypi:~/dasher/script $ ./find_button
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/pi/dasher/script/node_modules/node-dash-button/bin/findbutton'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

(same for sudo ./find_button)

**Comment by quavoce** [comment]
Ok, solved!

The issue is that nodejs is an old version when using the default package on Raspbian, so you have to upgrade to the latest version. The second issue I had above was installing npm as root (doesn't work) - I used a fresh Raspbian image and installed npm as Pi, and now the find_button command works. Here were my steps:

1. Write a new 2016-09-23-raspbian-jessie.img image to an SD card
2. Boot the Pi and SSH to it.
3. Run these commands:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libpcap-dev
sudo apt-get install npm
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install nodejs
git clone https://github.com/maddox/dasher.git
cd dasher
npm install

**Comment by LimeBlast** [comment]
Hi @quavoce, I wanted to thank you for this. I had exactly the same problem, and this helped me solve it.

Just as a future note to myself (and anyone else that is trying to get this to work on a Raspberry 1), the first 4 steps above work fine, but the 5th doesn't (the processor in the Pi 1 isn't powerful enough for node 7, or something like that), so instead you need to install node 4 using:

```
wget http://node-arm.herokuapp.com/node_latest_armhf.deb 
sudo dpkg -i node_latest_armhf.deb
```

After this you can go ahead and complete all the other steps, which should work correctly.
