### ISSUE TITLE
init.d script throws error on boot

### ISSUE THREAD

**Issue by hoveeman** [maddox/dasher#54]
I created the init.d script per your instructions for my raspberry pi 2. I can run this command manually and the script starts dasher correctly. 

`sudo /etc/init.d/dasher start` 

However, on boot of the raspberry pi, it throws this error into the /var/log/dasher.err file and dasher does not start

```
    at create_session (/home/pi/dasher/node_modules/node-dash-button/index.js:28:15)
    at register (/home/pi/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/home/pi/dasher/lib/dasher.js:12:21)
    at Object.<anonymous> (/home/pi/dasher/app.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

here is the beginning of my init.d dasher file.
```
#!/bin/sh
### BEGIN INIT INFO
# Provides: dasher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/home/pi/dasher"
cmd="DEBUG=* node app.js"
user="root"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

```

**Comment by hoveeman** [comment]
I created a systemd service for dasher and it is working well on boot. Here is my file if anyone is interested:

/etc/systemd/system/dasher.service

```
[Unit]
Description=Dasher
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/node /home/pi/dasher/app.js
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Once you create that file, you will need to reload, enable, and start it.

```
sudo systemctl daemon-reload
sudo systemctl enable dasher
sudo systemctl start dasher
```

You can check on the status of the service by typing this command.
`sudo systemctl status dasher -l`

**Comment by shnax** [comment]
Thanks! I was having the same issue and that got it working. Just had to change my systemd service to:

```
[Unit]
Description=Dasher
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/home/pi/dasher
ExecStart=/usr/bin/npm start
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by Aeefire** [comment]
For me both methods on a rpi jessie seem to fail.

Anyone has a solution?

`pi@raspberrypi:/var/log $ tail syslog
Jan 29 11:24:11 raspberrypi npm[1285]: npm ERR! code ELIFECYCLE
Jan 29 11:24:11 raspberrypi npm[1285]: npm WARN This failure might be due to the use of legacy binary "node"
Jan 29 11:24:11 raspberrypi npm[1285]: npm WARN For further explanations, please read
Jan 29 11:24:11 raspberrypi npm[1285]: /usr/share/doc/nodejs/README.Debian
Jan 29 11:24:11 raspberrypi npm[1285]: npm ERR!
Jan 29 11:24:11 raspberrypi npm[1285]: npm ERR! Additional logging details can be found in:
Jan 29 11:24:11 raspberrypi npm[1285]: npm ERR!     /home/pi/dasher/npm-debug.log
Jan 29 11:24:11 raspberrypi npm[1285]: npm ERR! not ok code 0
Jan 29 11:24:11 raspberrypi systemd[1]: dasher.service: main process exited, code=exited, status=1/FAILURE
Jan 29 11:24:11 raspberrypi systemd[1]: Unit dasher.service entered failed state.
pi@raspberrypi:/var/log $ tail /home/pi/dasher/npm-debug.log 
10 error You can get their info via:
10 error     npm owner ls dasher
10 error There is likely additional logging output above.
11 error System Linux 4.4.38-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/dasher
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
`
