### ISSUE TITLE
Dasher crash

### ISSUE THREAD

**Issue by hoveeman** [maddox/dasher#55]
After a few hours of running from the init.d script, I get this error in the dasher.err file. 

pi@pi:~ $ tail -f /var/log/dasher.err
                    && _.isEqual(packet.payload.payload.sender_ha.addr,
                                                                 ^

TypeError: Cannot read property 'addr' of undefined
    at PcapSession.<anonymous> (/home/pi/dasher/node_modules/node-dash-button/index.js:78:66)
    at emitOne (events.js:96:13)
    at PcapSession.emit (events.js:188:7)
    at PcapSession.on_packet_ready (/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/pcap.js:99:10)    at packet_ready (/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/pcap.js:44:14)
    at SocketWatcher.pcap_read_callback [as callback] (/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/pcap.js:64:45)

**Comment by hoveeman** [comment]
These are my node and npm versions. 

pi@pi:~ $ node -v
v6.9.1
pi@pi:~ $ npm -v
4.1.1

**Comment by seren** [comment]
I'm having this issue as well. Did you ever get it fixed?
