### ISSUE TITLE
I just stopped working...

### ISSUE THREAD

**Issue by ecrob527** [maddox/dasher#66]
I managed to get it working and then it just stopped working and I'm getting this error (Help Please!):

sudo npm run start
Password:

> dasher@1.3.0 start /Users/USER/dasher
> node app.js

module.js:590
    throw err;
    ^

SyntaxError: /Users/USER/dasher/config/config.json: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/USER/dasher/app.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.3.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

**Comment by EyMaddis** [comment]
You `config.json` has to be invalid, verify it with a JSON validation tool, like this: https://jsonformatter.curiousconcept.com/
