### ISSUE TITLE
Problem Installing.  

### ISSUE THREAD

**Issue by boydduk** [maddox/dasher#86]
/share/git/dasher] # npm install
|
> socketwatcher@0.3.0 install /share/CACHEDEV1_DATA/git/dasher/node_modules/node                                      -dash-button/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/nodejsv4/node/lib/node_modules/npm/node_modu                                      les/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/share/CACHEDEV1_DATA/.qpkg/nodejsv4/node/lib/node_modules/npm/node_modu                                      les/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/share/CACHEDEV1_DATA/.qpkg/nodejsv4/node/lib/node_modules/npm/node_modu                                      les/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
  File "/root/daily_build/64_21/4.3.3/SysUtil/Python-2.7.5-cross/install_path_fu                                      ll/lib/python2.7/compiler/__init__.py", line 29, in <module>
  File "/root/daily_build/64_21/4.3.3/SysUtil/Python-2.7.5-cross/install_path_fu                                      ll/lib/python2.7/compiler/transformer.py", line 29, in <module>
ImportError: No module named parser
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/share/CACHEDEV1_DATA/.qpkg/nodejsv                                      4/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                      s.js:200:12)
gyp ERR! System Linux 4.2.8
gyp ERR! command "/share/CACHEDEV1_DATA/.qpkg/nodejsv4/node/bin/node" "/share/CA                                      CHEDEV1_DATA/.qpkg/nodejsv4/node/lib/node_modules/npm/node_modules/node-gyp/bin/                                      node-gyp.js" "rebuild"
gyp ERR! cwd /share/CACHEDEV1_DATA/git/dasher/node_modules/node-dash-button/node                                      _modules/pcap/node_modules/socketwatcher
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 4.2.8
npm ERR! argv "/share/CACHEDEV1_DATA/.qpkg/nodejsv4/node/bin/node" "/usr/local/b                                      in/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketwatcher@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socketwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /share/CACHEDEV1_DATA/git/dasher/npm-debug.log

**Comment by boydduk** [comment]
I can't seem to run node-gyp, without typing node node-gyp?

**Comment by mrlohnes** [comment]
I am getting this same error when installing.

**Comment by strasp09** [comment]
I had the same problem but solved by installing libpcap-dev.
```
sudo apt-get install libpcap-dev
```
I did not notice the Setup section in README.md :p
