### ISSUE TITLE
Failure after button press is detected

### ISSUE THREAD

**Issue by rebel7580** [maddox/dasher#88]
Running on Raspberry Pi Zero.
I have my dash button defined as the "Debug Dash Button" in config.json.

Run Dasher. After some time (~30 -50 secs) the following error occurs.  Since it mentioned pcap and tcpdump wasn't installed, I installed tcpdump. However, that didn't fix the issue.

hvxl@rpia:~/dasher $ sudo npm run start

> dasher@1.4.1 start /home/hvxl/dasher
> node app.js

[2017-07-21T17:30:09.300Z] Debug Dash Button added.
warning: SIOCGIFADDR: en0: No such device - this may not actually work
[Error: SIOCGIFHWADDR: No such device]
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/home/hvxl/dasher/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/home/hvxl/dasher/node_modules/node-dash-button/index.js:28:15)
    at register (/home/hvxl/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/home/hvxl/dasher/lib/dasher.js:14:21)
    at Object.<anonymous> (/home/hvxl/dasher/app.js:8:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)

npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.4.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dasher@1.4.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dasher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hvxl/dasher/npm-debug.log

Log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dasher@1.4.1~prestart: dasher@1.4.1
6 silly lifecycle dasher@1.4.1~prestart: no script for prestart, continuing
7 info lifecycle dasher@1.4.1~start: dasher@1.4.1
8 verbose lifecycle dasher@1.4.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle dasher@1.4.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/hvxl/dasher/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle dasher@1.4.1~start: CWD: /home/hvxl/dasher
11 silly lifecycle dasher@1.4.1~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle dasher@1.4.1~start: Returned: code: 1  signal: null
13 info lifecycle dasher@1.4.1~start: Failed to exec start script
14 verbose stack Error: dasher@1.4.1 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid dasher@1.4.1
16 verbose cwd /home/hvxl/dasher
17 error Linux 4.4.50+
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
19 error node v5.7.1
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error dasher@1.4.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the dasher@1.4.1 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dasher package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dasher
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dasher
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rebel7580** [comment]
Noticing that the error came after only one button was added, I thought maybe there was something wrong with the config file. I originally had added my MAC address to the debug button, and left everything else alone.  This time I removed all other buttons so there was only the debug button.  This worked. The error was gone and dash presses were recognized!
