### ISSUE TITLE
Run script/find_button get Error:Cannot find module './build/Release/pcap_binding'

### ISSUE THREAD

**Issue by tonywk** [maddox/dasher#96]
I followed the installation steps exactly according to "Starting from a fresh Raspberry Pi Build?" installation section and have no problem. When I execute sudo ./script/find_button, below Error pops up:
Can you help me? Thanks!

pi@raspberrypi:~/dasher $ sudo ./script/find_button
module.js:339
    throw err;
    ^

Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/dasher/node_modules/node-dash-button/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by elmedico27** [comment]
Possibly dependencies didn't load correctly?  Try running `sudo npm rebuild` in your dasher directory.
